### ISSUE TITLE
old tests/streams not being removed when updated?

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-deploy#22]
It looks like old tests/streams are not being removed when an installation is updated.

![image](https://user-images.githubusercontent.com/8490792/123597407-99a9d100-d7f3-11eb-9d93-c277b9f7ec20.png)

I think the last two of this list are the old test content.

**Comment by louaybassbouss** [comment]
> It looks like old tests/streams are not being removed when an installation is updated.
> 
> ![image](https://user-images.githubusercontent.com/8490792/123597407-99a9d100-d7f3-11eb-9d93-c277b9f7ec20.png)
> 
> I think the last two of this list are the old test content.

@jpiesing this is not related to the installation, but because we still have the old tests in the [tests.csv](https://github.com/cta-wave/dpctf-tests/blob/master/tests.csv) file. We will remove the two folders `avc_15_30_60-local` and `avc_15_30_60-online`.  I propose to move the cenc tests into the same `avc_15_30_60-2021-06-11-online` and add a new folder `avc_15_30_60-2021-06-11-local` for downloaded content. wdyt?

**Comment by jpiesing** [comment]
> @jpiesing this is not related to the installation, but because we still have the old tests in the [tests.csv](https://github.com/cta-wave/dpctf-tests/blob/master/tests.csv) file. We will remove the two folders `avc_15_30_60-local` and `avc_15_30_60-online`. I propose to move the cenc tests into the same `avc_15_30_60-2021-06-11-online` and add a new folder `avc_15_30_60-2021-06-11-local` for downloaded content. wdyt?

Replacing avc_15_30_60-local with avc_15_30_60-2021-06-11-local is an improvement.
For cenc, I think we don't need most of them - see https://github.com/cta-wave/Test-Content-Generation/issues/39 .

**Comment by FritzHeiden** [comment]
I updated the tests.csv and regenerated the tests

**Comment by jpiesing** [comment]
OK.
