### ISSUE TITLE
Running Test Suite Under Windows - No APIs/tests during Configuration

### ISSUE THREAD

**Issue by javierbarellano4v** [cta-wave/dpctf-deploy#27]
I've built the Test Runner (and Observation Framework) in Windows 10 using WSL.

I was able to launch docker image and have a running container.

Next,  I launch into the landing page where I select "Configure Session". 

On the Configuration page,  the API field is not populated with any APIs so I can't select any APIs (please see attached image)

I also noticed that the subdirectory /tests is empty, should it be empty?
 
Any help is greatly appreciated?

Thank you.
Javier

![Session Configuration Snapshot](https://user-images.githubusercontent.com/97479879/159938165-d0d50769-2bf7-43d6-92a5-10df658b27e8.JPG)

**Comment by jpiesing** [comment]
@gitwjr Bill, does any of this sound familiar?
@louaybassbouss do you have any suggestions?

**Comment by javierbarellano4v** [comment]
Thanks Jon for bringing attention to my issue.

Digging around, I did notice that in 'import.sh' there is some code to download tests but it has now been commented out.

Is the Python script that is now invoked in this shell script also download tests or is this done somewhere else?

Just trying to figure out if I have something misconfigured somewhere...


Thanks.

**Comment by jpiesing** [comment]
@javierbarellano4v I suggest you extract the logs from docker and see if there are any error messages there. If there's nothing obvious, you might attach them here?

**Comment by javierbarellano4v** [comment]
Not the most orthodox thing to do - but I pulled out the code from that shell script and executed manually:

clone https://github.com/cta-wave/dpctf-tests dpctf
mv dpctf/generated/* tests
mv dpctf/test-config.json tests

Re-launched Test Runner on a laptop (running Chrome with no camera) and the following appeared:

![Session Config webpage](https://user-images.githubusercontent.com/97479879/160002703-ba79c5d9-230d-4a8e-98b3-ab4cbe94c50b.jpg)

Then ultimately I selected a  single sequential playback test and video appeared with the following result:

![Results webpage](https://user-images.githubusercontent.com/97479879/160003123-6d184fb7-cfc6-4055-8d5d-54b78794f000.jpg)

So, absent having test files incorporated or downloaded via scripts automatically (which I'll need to resolve this at some point),  I think I made progress - now need to record and run observation framework.

Thanks.

**Comment by gitwjr** [comment]
@javierbarellano4v @jpiesing When running under Windows DockerDesktop does need WSL2 to run successfully. And I found that **everything** needs to be done using a Windows Terminal. If you use a Linux Terminal/BASH there appears to be an interaction between Windows/WSL and Linux that messes things up which resulted in my having to reload everything to get tests to run again. The test would run but if I exited and restarted later Docker wouldn't operate correctly. Basically when they say do not use WSL, what they mean us use Windows Terminal/PowerShell (I used Terminal not PowerShell. It seemed to work better but that could be pure coincidence due to other things I was trying).DO NOT use Linux BASH. Also right click on it and select "Run as Administrator" if you aren't. 

I see you mentioned using import.sh. I used both "./build.bat master latest"  and "./import.bat" in a Windows Terminal which worked for me. ...sh did not work correctly/reliably in a Windows Terminal and using a Linux terminal to run the ...sh build/imports led to other problems (often the "run once, then fail" problem mentioned above. 

Also, I found that when Windows Terminal hangs up Control + C allowed a graceful exit.  

Make sure you use docker stop <container_name> (in Windows Terminal) when done. If Windows updates before you come back things get screwed up. Happened several times to me. 

My full instructions posed here https://github.com/cta-wave/dpctf-deploy/files/7653078/Setup.on.Windows. I can't say exactly why what I did worked (or what I did earlier didn't) but I tested these instructions after a total wipe and reload of everything and it worked. I included some hints and asides in them.

**Comment by javierbarellano4v** [comment]
@gitwjr  I apologize for the delayed response. This is very helpful information! I appreciate it. 

Just to note, the link to your full instructions yielded a missing page.  I had really hoped to access that writeup. Alternatively, I'm open to getting it via email.

Yes, one has to stick a Windows Terminal/Powershell.  I may need to deploy on a different host and start over and make note of every step as you did. Hopefully I can get ahold of your writeup on the GitHub or otherwise.

Thanks so much for sharing all this information.

**Comment by jpiesing** [comment]
@javierbarellano4v https://github.com/cta-wave/dpctf-deploy/files/7653078/Setup.on.Windows.using.WSL2.docx

**Comment by javierbarellano4v** [comment]
@jpiesing Thank you!

**Comment by javierbarellano4v** [comment]
hopefully one last question....

When running the observation framework, during analysis the following appears:

Serious error is detected, when analysing ['laptop1.MOV']!Error: Failed to get configuration file from test runner 404

I'm sure something is misconfigured .....

Thanks,.

**Comment by gitwjr** [comment]
Just a thought. You must use the same video you recorded during the Test Runner run when you run the OF. There is an ID for the test that is compared. No compare, no valid config file. I wanted to make sure my set up was correct. I asked for a “known good video” to test with. They said not possible. They must match.

**Comment by jpiesing** [comment]
Perhaps have a look at the log file from the docker image & see if there's anything there about why the server was unable to access the configuration file?

**Comment by javierbarellano4v** [comment]
Thanks @jpiesing..., indeed, log has info.

**Comment by yanj-github** [comment]
> 

Error code 404 seem that the observation framework cannot find the test runner server. OF needs to get the configuration file from TR when it start to observing a test. 
We suggest to install TR and OF on same machine so that it can access from http://localhost:8000/ as localhost is a default TR server address on OF.
Can you try "http://localhost:8000" on the platfrom (web browser or ping) where you have OF, see if you can see TR please?

**Comment by javierbarellano4v** [comment]
@yanj-github Yes, good point. 

I was able to successfully do a full analysis in OF on a test run.  But, I had to move the test-config.json file from /dpct to /dpct-deploy-master and thereafter OF run without a problem. Probably an unorthodox move but it worked.

**Comment by javierbarellano4v** [comment]
@FritzHeiden Thank you!

**Comment by javierbarellano4v** [comment]
Question: The tests enumerated here at https://github.com/cta-wave/dpctf-tests/blob/master/tests.csv show up in the test runner, most or all, as expected. 

So the testcases enumerated in DPCAT 21,  are these testcases a different set? additional? 

Thanks.

**Comment by javierbarellano4v** [comment]
Think I can answer my own question, these testcases 8.15+ (in DPCT 21) are additional testcases.

**Comment by louaybassbouss** [comment]
@javierbarellano4v yes these are additional tests but they will be merged soon into the main branch. The DPCAT new tests are provided for now in [dpcat](https://github.com/cta-wave/dpctf-tests/tree/dpcat-staging) branch. Once the testing and validation with observation Framework ist completed, they will be merge into the main branch. At the end, we will have all DPC tests in one repo.

**Comment by javierbarellano4v** [comment]
@louaybassbouss Thanks for confirming!

**Comment by javierbarellano4v** [comment]
I have a somewhat naïve question. Where is the chunk encoding done? In mezzanine phase or in the test content phase?

**Comment by louaybassbouss** [comment]
> I have a somewhat naïve question. Where is the chunk encoding done? In mezzanine phase or in the test content phase?

In test content phase

**Comment by javierbarellano4v** [comment]
@louaybassbouss Thank you. Appreciate all your hard work on this framework

**Comment by louaybassbouss** [comment]
> I think I know the answer to this but just in case.
> 
> When I run tests, I get some results labeled/titled API tests. Is the testrunner running the WMAS tests (or a subset) during a run?
> 
> Thanks.

@javierbarellano4v yes indeed this is confusing the API tests are more related to WMAS. We now renamed to "Test Group" if ok for you please close this issue.
