### ISSUE TITLE
Network connectivity issue on WSL environment

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-deploy#63]
I am adding this issue for @gitwjr.
The main issue he is facing is, OF cannot connect to test runner when it has installed on WSL inside docker.

Bill had followed quick start guide: OF inside docker on WSL and test runner is inside another docker on same WSL.
OF cannot run because it cannot talk to test runner on localhost. 
Bill did try different IP addresses but did not work. 

However, OF that set up native to WSL can talk to test runner on localhost.
@FritzHeiden will you be able to help on this please?

**Comment by jpiesing** [comment]
I'm wondering if this should be "won't fix" or "documentation" and that mixing Docker Desktop and non-docker but WSL deployments on Windows should be (strongly?) discouraged due to exactly this sort of issue. IMHO the priority should be solving any issues with the docker version of the OF on Windows.

**Comment by gitwjr** [comment]
Since what I am testing is the QS Guide instructions and I followed it explicitly (as far as I know going step by step) wherever TR and OF are running is per the guide. Either the Guide is unclear or it needs clearer instructions.  Docker shows a single image (dpctf tag latest) and no containers. Do I have to start dpctf somehow? Should be LSXX not be running? My show 
![Screenshot 2024-02-29 090540 features](https://github.com/cta-wave/dpctf-deploy/assets/15801730/4965eb36-cae9-4e9b-a48c-605ec8fa8664)

**Comment by jpiesing** [comment]
I can quite believe that there's something that is implicit and obvious to experts that is not clear enough for non-experts. We just need to find it. That probably requires a screen sharing session between Bill and someone at Fraunhofer, or even someone at Fraunhofer doing the steps at the same time as Bill.

**Comment by gitwjr** [comment]
Using .\build.bat master latest, .\import.bat and .\build-dof.bat for WSL/Windows works cleanly. See #84 comments on 3/1/2024 by @gitwjr

**Comment by FritzHeiden** [comment]
I pushed a fix for the `analyse-recordings.sh` script that may fix this issue https://github.com/cta-wave/dpctf-deploy/pull/87
Please have another try

**Comment by gitwjr** [comment]
After pulling the latest updates (as of a month ago) I was able to run the script on 2 different PCs running WSL according to the latest Windows/WSL instructions (yet to be posted). Therefore I believe we can close this issue.

**Comment by gitwjr** [comment]
Done. Close
